### ISSUE TITLE
Not able to initialize terraform

### ISSUE THREAD

**Issue by rvarun95** [micro-frontends-demo/infra#2]
While performing 'terraform init', I got the below error.

Initializing modules...

Initializing the backend...

Error: No valid credential sources found for AWS Provider.
        Please see https://terraform.io/docs/providers/aws/index.html for more information on
        providing credentials for the AWS Provider

**Comment by camjackson** [comment]
Yes, you need to have your own AWS account, and configure your AWS credentials as you would if you were going to use the AWS CLI. The link you pasted explains further.

In case it's not clear, you only need to use this infra repo if you're trying to provision your own stack of micro frontends. And it won't work out of the box because it's hardcoded to deploy to a domain that you don't own. I will update the readme to make this a bit clearer as you're not the first person with this question.
